### PR TITLE
Added UK Gov Web Archive to Code.js

### PR DESCRIPTION
**Pull request by tom-s-ukgwa**
Extended it with another function to check https://webarchive.nationalarchives.gov.uk/ URLs

### CODE REVIEW

**Comment by anjackson** [comment]
Excellent, thanks @tom-s-ukgwa!  Now I'll have to remember how to roll a release!?

**Comment by anjackson** [comment]
ahem that's better.

**Comment by tom-s-ukgwa** [comment]
☺ Good luck with that one, Andy – that’s well outside my skillset!

**Comment by anjackson** [comment]
Cool, I think that worked. V10 now live https://chrome.google.com/webstore/detail/ukwa-google-sheets-utilit/dghejanopbolppcgmihfhnaedjfjoaik and includes `WEBARCHIVE_STATUS_UKGWA`

**Pull request merged**
